// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gPere25tZXJ8DN5wLAbNNx
// Component: z-inCbAmtHs6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: gPere25tZXJ8DN5wLAbNNx/projectcss
import sty from "./PlasmicVerbumFooter.module.css"; // plasmic-import: z-inCbAmtHs6/css

import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: WNrOKOGZa0w2/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: Db8zntDAjUz9/icon

createPlasmicElementProxy;

export type PlasmicVerbumFooter__VariantMembers = {};
export type PlasmicVerbumFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicVerbumFooter__VariantsArgs;
export const PlasmicVerbumFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicVerbumFooter__ArgsType = {};
type ArgPropType = keyof PlasmicVerbumFooter__ArgsType;
export const PlasmicVerbumFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicVerbumFooter__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultVerbumFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVerbumFooter__RenderFunc(props: {
  variants: PlasmicVerbumFooter__VariantsArgs;
  args: PlasmicVerbumFooter__ArgsType;
  overrides: PlasmicVerbumFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__urFkr)}>
        <div className={classNames(projectcss.all, sty.freeBox__jYqv4)}>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/verbum_onboarding/images/screenshot20231204At123248AmRemovebgpng.png",
              fullWidth: 2712,
              fullHeight: 1792,
              aspectRatio: undefined
            }}
          />
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__m32Wi)}>
        <div className={classNames(projectcss.all, sty.freeBox__a1Vzo)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__v1Kdc
            )}
            onClick={async event => {
              const $steps = {};

              $steps["goToContact"] = true
                ? (() => {
                    const actionArgs = { destination: `/contact` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToContact"] != null &&
                typeof $steps["goToContact"] === "object" &&
                typeof $steps["goToContact"].then === "function"
              ) {
                $steps["goToContact"] = await $steps["goToContact"];
              }
            }}
          >
            {"Contact"}
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__aRmi7)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__hQryZ
          )}
          onClick={async event => {
            const $steps = {};

            $steps["goToCareers"] = true
              ? (() => {
                  const actionArgs = { destination: `/careers` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToCareers"] != null &&
              typeof $steps["goToCareers"] === "object" &&
              typeof $steps["goToCareers"].then === "function"
            ) {
              $steps["goToCareers"] = await $steps["goToCareers"];
            }
          }}
        >
          {"Careers"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___12CSu)}>
        <Icon7Icon
          className={classNames(projectcss.all, sty.svg__zTw5Y)}
          onClick={event => {
            window.open('https://twitter.com/VerbumLabs', '_blank');
          }}
          role={"img"}
        />

        <Icon8Icon
          className={classNames(projectcss.all, sty.svg__b8Btb)}
          onClick={event => {
            window.open('https://discord.gg/cvzUAkzcS7', '_blank');
          }}
          role={"img"}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVerbumFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVerbumFooter__VariantsArgs;
    args?: PlasmicVerbumFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVerbumFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVerbumFooter__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVerbumFooter__ArgProps,
          internalVariantPropNames: PlasmicVerbumFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVerbumFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVerbumFooter";
  } else {
    func.displayName = `PlasmicVerbumFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicVerbumFooter = Object.assign(
  // Top-level PlasmicVerbumFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicVerbumFooter
    internalVariantProps: PlasmicVerbumFooter__VariantProps,
    internalArgProps: PlasmicVerbumFooter__ArgProps
  }
);

export default PlasmicVerbumFooter;
/* prettier-ignore-end */
